package providers

import "strings"

const footballTeamMonchengladbach = "묀헨글라트바흐"

// footballTeamNames maps English team names to Korean names.
// Keys are lowercase for case-insensitive lookup.
var footballTeamNames = map[string]string{
	// EPL
	"arsenal":                 "아스널",
	"aston villa":             "아스톤 빌라",
	"afc bournemouth":         "본머스",
	"bournemouth":             "본머스",
	"brentford":               "브렌트퍼드",
	"brighton":                "브라이튼",
	"brighton & hove albion":  "브라이튼",
	"burnley":                 "번리",
	"chelsea":                 "첼시",
	"crystal palace":          "크리스탈 팰리스",
	"everton":                 "에버턴",
	"fulham":                  "풀럼",
	"ipswich town":            "입스위치",
	"leicester city":          "레스터",
	"liverpool":               "리버풀",
	"luton town":              "루턴",
	"manchester city":         "맨시티",
	"manchester united":       "맨유",
	"man city":                "맨시티",
	"man united":              "맨유",
	"newcastle united":        "뉴캐슬",
	"newcastle":               "뉴캐슬",
	"nottingham forest":       "노팅엄",
	"sheffield united":        "셰필드",
	"southampton":             "사우스햄튼",
	"tottenham hotspur":       "토트넘",
	"tottenham":               "토트넘",
	"west ham united":         "웨스트햄",
	"west ham":                "웨스트햄",
	"wolverhampton wanderers": "울버햄튼",
	"wolverhampton":           "울버햄튼",
	"wolves":                  "울버햄튼",

	// La Liga
	"atletico madrid":  "아틀레티코",
	"atlético madrid":  "아틀레티코",
	"athletic bilbao":  "빌바오",
	"athletic club":    "빌바오",
	"barcelona":        "바르셀로나",
	"fc barcelona":     "바르셀로나",
	"real betis":       "베티스",
	"cadiz":            "카디스",
	"celta vigo":       "셀타",
	"elche":            "엘체",
	"getafe":           "헤타페",
	"girona":           "지로나",
	"granada":          "그라나다",
	"las palmas":       "라스팔마스",
	"mallorca":         "마요르카",
	"osasuna":          "오사수나",
	"rayo vallecano":   "라요",
	"real madrid":      "레알 마드리드",
	"real sociedad":    "소시에다드",
	"sevilla":          "세비야",
	"valencia":         "발렌시아",
	"villarreal":       "비야레알",
	"almeria":          "알메리아",
	"deportivo alaves": "알라베스",
	"alaves":           "알라베스",
	"leganes":          "레가네스",
	"real valladolid":  "바야돌리드",
	"espanyol":         "에스파뇰",

	// Serie A
	"ac milan":       "AC밀란",
	"milan":          "AC밀란",
	"as roma":        "로마",
	"roma":           "로마",
	"atalanta":       "아탈란타",
	"bologna":        "볼로냐",
	"cagliari":       "칼리아리",
	"cremonese":      "크레모네세",
	"empoli":         "엠폴리",
	"fiorentina":     "피오렌티나",
	"frosinone":      "프로시노네",
	"genoa":          "제노아",
	"hellas verona":  "베로나",
	"inter milan":    "인테르",
	"inter":          "인테르",
	"internazionale": "인테르",
	"juventus":       "유벤투스",
	"lazio":          "라치오",
	"lecce":          "레체",
	"monza":          "몬자",
	"napoli":         "나폴리",
	"parma":          "파르마",
	"salernitana":    "살레르니타나",
	"sampdoria":      "삼프도리아",
	"sassuolo":       "사수올로",
	"spezia":         "스페치아",
	"torino":         "토리노",
	"udinese":        "우디네세",
	"venezia":        "베네치아",
	"como":           "코모",
	"verona":         "베로나",

	// Bundesliga
	"bayern munich":            "뮌헨",
	"bayern münchen":           "뮌헨",
	"fc bayern münchen":        "뮌헨",
	"bayer leverkusen":         "레버쿠젠",
	"leverkusen":               "레버쿠젠",
	"borussia dortmund":        "도르트문트",
	"dortmund":                 "도르트문트",
	"rb leipzig":               "라이프치히",
	"leipzig":                  "라이프치히",
	"eintracht frankfurt":      "프랑크푸르트",
	"frankfurt":                "프랑크푸르트",
	"sc freiburg":              "프라이부르크",
	"freiburg":                 "프라이부르크",
	"vfb stuttgart":            "슈투트가르트",
	"stuttgart":                "슈투트가르트",
	"tsg hoffenheim":           "호펜하임",
	"hoffenheim":               "호펜하임",
	"union berlin":             "베를린",
	"1. fc union berlin":       "베를린",
	"vfl wolfsburg":            "볼프스부르크",
	"wolfsburg":                "볼프스부르크",
	"werder bremen":            "브레멘",
	"sv werder bremen":         "브레멘",
	"borussia m'gladbach":      footballTeamMonchengladbach,
	"borussia mönchengladbach": footballTeamMonchengladbach,
	"gladbach":                 footballTeamMonchengladbach,
	"fc augsburg":              "아우크스부르크",
	"augsburg":                 "아우크스부르크",
	"mainz 05":                 "마인츠",
	"1. fsv mainz 05":          "마인츠",
	"vfl bochum":               "보훔",
	"bochum":                   "보훔",
	"1. fc heidenheim":         "하이덴하임",
	"heidenheim":               "하이덴하임",
	"fc köln":                  "쾰른",
	"1. fc köln":               "쾰른",
	"cologne":                  "쾰른",
	"darmstadt":                "다름슈타트",
	"sv darmstadt 98":          "다름슈타트",
	"fc st. pauli":             "장크트파울리",
	"holstein kiel":            "킬",

	// K-League
	"jeonbuk hyundai motors":  "전북",
	"jeonbuk":                 "전북",
	"jeonbuk fc":              "전북",
	"ulsan hd":                "울산",
	"ulsan hd fc":             "울산",
	"ulsan hyundai":           "울산",
	"ulsan hyundai fc":        "울산",
	"ulsan":                   "울산",
	"pohang steelers":         "포항",
	"pohang steelers fc":      "포항",
	"pohang":                  "포항",
	"fc seoul":                "FC서울",
	"incheon united":          "인천",
	"incheon":                 "인천",
	"daejeon citizen":         "대전",
	"daejeon":                 "대전",
	"gangwon fc":              "강원",
	"gangwon":                 "강원",
	"suwon fc":                "수원FC",
	"suwon samsung":           "수원삼성",
	"gwangju fc":              "광주",
	"gwangju":                 "광주",
	"jeju united":             "제주",
	"jeju":                    "제주",
	"daegu fc":                "대구",
	"daegu":                   "대구",
	"gimcheon sangmu":         "김천",
	"gimcheon":                "김천",
	"bucheon fc":              "부천",
	"bucheon fc 1995":         "부천",
	"bucheon":                 "부천",
	"fc anyang":               "안양",
	"anyang fc":               "안양",
	"anyang":                  "안양",
	"chungnam asan":           "충남아산",
	"asan":                    "충남아산",
	"seoul e-land":            "서울이랜드",
	"seoul e-land fc":         "서울이랜드",
	"suwon samsung bluewings": "수원삼성",
	"jeonnam dragons":         "전남",
	"jeonnam":                 "전남",
	"jeju sk":                 "제주",

	// Champions League (additional international teams)
	"psg":                 "PSG",
	"paris saint-germain": "PSG",
	"paris sg":            "PSG",
	"real madrid cf":      "레알 마드리드",
	"sporting cp":         "스포르팅",
	"sporting":            "스포르팅",
	"benfica":             "벤피카",
	"porto":               "포르투",
	"fc porto":            "포르투",
	"ajax":                "아약스",
	"psv eindhoven":       "PSV",
	"psv":                 "PSV",
	"celtic":              "셀틱",
	"rangers":             "레인저스",
	"red star belgrade":   "츠르베나 즈베즈다",
	"galatasaray":         "갈라타사라이",
	"shakhtar donetsk":    "샤흐타르",
	"red bull salzburg":   "잘츠부르크",
	"club brugge":         "클럽 브뤼헤",
	"brugge":              "클럽 브뤼헤",
	"young boys":          "영보이스",
	"copenhagen":          "코펜하겐",
	"feyenoord":           "페예노르트",
	"bodø/glimt":          "보되/글림트",
	"bodo/glimt":          "보되/글림트",
	"dinamo zagreb":       "디나모 자그레브",
	"sparta prague":       "스파르타 프라하",
	"slovan bratislava":   "슬로반 브라티슬라바",
	"sturm graz":          "슈투름 그라츠",
	"brest":               "브레스트",
	"stade brestois":      "브레스트",
	"lille":               "릴",
	"monaco":              "모나코",
	"as monaco":           "모나코",
	"girona fc":           "지로나",
}

// TranslateTeamName looks up the Korean name for an English football team name.
// Returns the Korean name if found, or the original name unchanged.
func TranslateTeamName(englishName string) string {
	key := strings.TrimSpace(strings.ToLower(englishName))
	if korean, ok := footballTeamNames[key]; ok {
		return korean
	}
	return englishName
}
